export const summaryBar = 'flex items-center justify-between px-6 py-4 border-t border-gray-800 bg-gray-900/95 backdrop-blur-sm'
export const totalLabel = 'text-sm text-gray-400'
export const totalAmount = 'text-xl font-bold text-gray-100 ml-2'
export const barActions = 'flex items-center gap-3'
export const btnExit = 'rounded-xl px-4 py-2 text-sm font-medium text-gray-300 bg-gray-800 hover:bg-gray-700 transition-colors'
export const btnSave = 'rounded-xl px-4 py-2 text-sm font-medium text-white bg-indigo-600 hover:bg-indigo-500 disabled:opacity-50 disabled:cursor-not-allowed transition-colors'
